; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
default_envs = m5stack-cores3

[sd-updater]
build_flags = 
	-DENABLE_SD_UPDATER
lib_deps = 
	tobozo/M5Stack-SD-Updater
	https://github.com/tobozo/ESP32-targz

[env:m5stack-core2]
platform = espressif32@6.3.2
board = m5stack-core2
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
board_build.partitions = default_16MB.csv
monitor_filters = esp32_exception_decoder
build_flags = 
	-DBOARD_HAS_PSRAM
	-DUSE_SERVO
	-DENABLE_WAKEWORD
	-DARDUINOJSON_DEFAULT_NESTING_LIMIT=100
	;-DCORE_DEBUG_LEVEL=5		;Verbose
	;-DUSE_AUDIO_MODULE			; Audio Moduleで外部マイク、スピーカーを使う場合。lib_depsのModule-Audioの有効化も必要。
	;-DENABLE_TAP_DETECT		; 加速度センサによるダブルタップの検出

lib_deps = 
	m5stack/M5Unified @ 0.2.7
	earlephilhower/ESP8266Audio @ ^1.9.7
	bblanchon/ArduinoJson @ ^7
	ESP32WebServer
	https://github.com/MechaUma/SimpleVox
	FastLED/FastLED@^3.5.0
	https://github.com/ronron-gh/esp8266FTPServer
	esp32-camera
	tobozo/YAMLDuino@^1.4.2
	https://github.com/stack-chan/stackchan-arduino.git
	;m5stack/Module-Audio@^0.0.1
lib_ldf_mode = deep

[env:m5stack-core2-sdu]
extends = env:m5stack-core2, sd-updater
build_flags = ${env:m5stack-core2.build_flags} ${sd-updater.build_flags}
lib_deps = 
	${env:m5stack-core2.lib_deps} ${sd-updater.lib_deps}

[env:m5stack-cores3]
platform = espressif32@6.3.2
board = esp32s3box
framework = arduino
board_build.arduino.memory_type = qio_qspi
board_build.arduino.partitions = my_cores3_16MB.csv
monitor_filters = esp32_exception_decoder
board_build.f_flash = 80000000L
board_build.filesystem = spiffs
build_flags = 
	-DBOARD_HAS_PSRAM
	-DUSE_SERVO
	-DARDUINO_M5STACK_CORES3
	-DENABLE_CAMERA
	-DARDUINOJSON_DEFAULT_NESTING_LIMIT=100
	;-DENABLE_TAP_DETECT		; 加速度センサによるダブルタップの検出 (※CoreS3-SEは加速度センサ非搭載)
monitor_speed = 115200
upload_speed = 1500000
lib_deps = 
	m5stack/M5Unified @ 0.1.17
	earlephilhower/ESP8266Audio @ ^1.9.7
	bblanchon/ArduinoJson @ ^7
	ESP32WebServer
	https://github.com/MechaUma/SimpleVox
	FastLED/FastLED@^3.5.0
	https://github.com/ronron-gh/esp8266FTPServer
	esp32-camera
	tobozo/YAMLDuino@^1.4.2
	https://github.com/stack-chan/stackchan-arduino.git
lib_ldf_mode = deep


[env:m5stack-atoms3r]
platform    = espressif32@6.11.0
board       = m5stack-atoms3
framework   = arduino

; ファイルシステム
;board_build.filesystem = littlefs
board_build.filesystem = spiffs

; PSRAM 有効化
board_build.arduino.memory_type = qio_opi
board_build.flash_mode          = qio
board_build.psram_type          = opi

monitor_speed = 115200
;monitor_filters = esp32_exception_decoder		// シリアルモニタに何も出なくなった

build_flags =
	-DESP32S3
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DARDUINO_USB_CDC_ON_BOOT=1      ; USB CDC を起動時から有効化
	-DARDUINO_USB_MODE=1             ; USB シリアルポートを使う
	-DARDUINO_M5STACK_ATOMS3R
	;-DENABLE_WAKEWORD               ; ウェイクワードは未対応
	-DARDUINOJSON_DEFAULT_NESTING_LIMIT=100
	;-DCAT_FACE
	;-DENABLE_TAP_DETECT			 ; 加速度センサによるダブルタップの検出

lib_deps =
	m5stack/M5Unified @ 0.2.7
	earlephilhower/ESP8266Audio @ ^1.9.7
	bblanchon/ArduinoJson @ ^7
	ESP32WebServer
	;https://github.com/MechaUma/SimpleVox    ; ウェイクワードは未対応
	FastLED/FastLED@^3.5.0
	https://github.com/ronron-gh/esp8266FTPServer
	esp32-camera
	tobozo/YAMLDuino@^1.4.2
	https://github.com/stack-chan/stackchan-arduino.git
lib_ldf_mode = deep
